In [9]:
pip install wooldridge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
import pandas as pd
import numpy as np
import wooldridge as wd

In [64]:
wage = wd.data('wage1')[['wage','educ','exper']]
wage

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [67]:
y = wage ['wage'].to_numpy()
x = wage [['educ','exper']].to_numpy()
u = wage.to_numpy()

In [68]:
x

array([[11,  2],
       [12, 22],
       [11,  2],
       ...,
       [15, 13],
       [16,  5],
       [14,  5]])

In [69]:
y

array([ 3.0999999 ,  3.24000001,  3.        ,  6.        ,  5.30000019,
        8.75      , 11.25      ,  5.        ,  3.5999999 , 18.18000031,
        6.25      ,  8.13000011,  8.77000046,  5.5       , 22.20000076,
       17.32999992,  7.5       , 10.63000011,  3.5999999 ,  4.5       ,
        6.88000011,  8.47999954,  6.32999992,  0.52999997,  6.        ,
        9.56000042,  7.78000021, 12.5       , 12.5       ,  3.25      ,
       13.        ,  4.5       ,  9.68000031,  5.        ,  4.67999983,
        4.26999998,  6.1500001 ,  3.50999999,  3.        ,  6.25      ,
        7.80999994, 10.        ,  4.5       ,  4.        ,  6.38000011,
       13.69999981,  1.66999996,  2.93000007,  3.6500001 ,  2.9000001 ,
        1.63      ,  8.60000038,  5.        ,  6.        ,  2.5       ,
        3.25      ,  3.4000001 , 10.        , 21.62999916,  4.38000011,
       11.71000004, 12.39000034,  6.25      ,  3.71000004,  7.78000021,
       19.97999954,  6.25      , 10.        ,  5.71000004,  2.  

In [70]:
u

array([[ 3.0999999 , 11.        ,  2.        ],
       [ 3.24000001, 12.        , 22.        ],
       [ 3.        , 11.        ,  2.        ],
       ...,
       [ 4.67000008, 15.        , 13.        ],
       [11.56000042, 16.        ,  5.        ],
       [ 3.5       , 14.        ,  5.        ]])

In [71]:
X = np.c_[np.ones(len(x)),x]

In [72]:
X

array([[ 1., 11.,  2.],
       [ 1., 12., 22.],
       [ 1., 11.,  2.],
       ...,
       [ 1., 15., 13.],
       [ 1., 16.,  5.],
       [ 1., 14.,  5.]])

In [73]:
BETAS = np.linalg.inv(X.T.dot(X)).dot(X.T.dot(y))
BETAS #(X^T * X)^-1 * X^T*y #MCO

array([-3.39053946,  0.64427208,  0.0700954 ])

In [83]:
X.dot(BETAS)

array([ 3.83664416,  5.88282415,  3.83664416,  4.84783456,  4.83139322,
        7.54867231,  9.25778884,  4.69120242,  6.16320574,  9.10418453,
        7.47857691,  5.19528371,  5.39215638,  5.60244257,  6.51368272,
        7.89914929,  5.0416794 ,  6.10652385,  5.25196559,  6.8641597 ,
        5.1117748 ,  6.37349193,  7.54867231,  4.55101163,  6.28998302,
        7.12809993,  7.6888631 ,  9.09077102,  8.37640355,  2.39449571,
        7.2414637 ,  5.76946039,  6.10652385,  4.83139322,  4.55101163,
        8.45991246,  5.39215638,  1.92026928,  5.83955578,  5.1117748 ,
        4.55101163,  5.74263336,  6.75079593,  6.85074619,  5.75604687,
        7.67544959,  3.12227669,  6.8641597 ,  6.26012816,  5.39215638,
        5.60244257,  7.12809993,  5.39215638,  4.83139322,  4.48091624,
        6.48382786,  6.98790914,  2.67487729,  8.76712106,  7.40848152,
        7.78881336,  8.57327622,  5.57561555,  3.96342144,  6.26012816,
        7.45174989,  7.40848152,  6.09311034,  7.61876771,  4.55

In [84]:
y_est = X.dot(BETAS)

In [85]:
y

array([ 3.0999999 ,  3.24000001,  3.        ,  6.        ,  5.30000019,
        8.75      , 11.25      ,  5.        ,  3.5999999 , 18.18000031,
        6.25      ,  8.13000011,  8.77000046,  5.5       , 22.20000076,
       17.32999992,  7.5       , 10.63000011,  3.5999999 ,  4.5       ,
        6.88000011,  8.47999954,  6.32999992,  0.52999997,  6.        ,
        9.56000042,  7.78000021, 12.5       , 12.5       ,  3.25      ,
       13.        ,  4.5       ,  9.68000031,  5.        ,  4.67999983,
        4.26999998,  6.1500001 ,  3.50999999,  3.        ,  6.25      ,
        7.80999994, 10.        ,  4.5       ,  4.        ,  6.38000011,
       13.69999981,  1.66999996,  2.93000007,  3.6500001 ,  2.9000001 ,
        1.63      ,  8.60000038,  5.        ,  6.        ,  2.5       ,
        3.25      ,  3.4000001 , 10.        , 21.62999916,  4.38000011,
       11.71000004, 12.39000034,  6.25      ,  3.71000004,  7.78000021,
       19.97999954,  6.25      , 10.        ,  5.71000004,  2.  

In [86]:
y - y_est

array([-7.36644256e-01, -2.64282415e+00, -8.36644160e-01,  1.15216544e+00,
        4.68606975e-01,  1.20132769e+00,  1.99221116e+00,  3.08797577e-01,
       -2.56320583e+00,  9.07581577e+00, -1.22857691e+00,  2.93471641e+00,
        3.37784407e+00, -1.02442571e-01,  1.56863180e+01,  9.43085063e+00,
        2.45832060e+00,  4.52347626e+00, -1.65196569e+00, -2.36415970e+00,
        1.76822532e+00,  2.10650762e+00, -1.21867239e+00, -4.02101166e+00,
       -2.89983019e-01,  2.43190049e+00,  9.11371087e-02,  3.40922898e+00,
        4.12359645e+00,  8.55504295e-01,  5.75853630e+00, -1.26946039e+00,
        3.57347645e+00,  1.68606785e-01,  1.28988197e-01, -4.18991248e+00,
        7.57843712e-01,  1.58973071e+00, -2.83955578e+00,  1.13822520e+00,
        3.25898831e+00,  4.25736664e+00, -2.25079593e+00, -2.85074619e+00,
        6.23953240e-01,  6.02455022e+00, -1.45227673e+00, -3.93415963e+00,
       -2.61012806e+00, -2.49215629e+00, -3.97244258e+00,  1.47190045e+00,
       -3.92156383e-01,  

In [87]:
error_est = y - y_est

In [88]:
y.shape #n #n-k-1 #k = 2 

(526,)

In [89]:
sum(error_est ** 2) #numerador

5548.159788779683

In [94]:
sum(error_est ** 2) / (y.shape [0]- 2 - 1)

10.608336116213543

In [96]:
sigma_cudr = sum(error_est ** 2) / (y.shape [0]- 2 - 1)

In [108]:
np.diag(np.sqrt(sigma_cudr * (np.linalg.inv((X.T.dot(X))))))

<ipython-input-108-64c018b8bf51>:1: RuntimeWarning: invalid value encountered in sqrt
  np.diag(np.sqrt(sigma_cudr * (np.linalg.inv((X.T.dot(X))))))


array([0.76656609, 0.05380607, 0.01097764])

In [110]:
u_estandar = np.diag(np.sqrt(sigma_cudr * (np.linalg.inv((X.T.dot(X))))))

<ipython-input-110-7a53f1057384>:1: RuntimeWarning: invalid value encountered in sqrt
  u_estandar = np.diag(np.sqrt(sigma_cudr * (np.linalg.inv((X.T.dot(X))))))


In [111]:
BETAS / u_estandar #t

array([-4.423023  , 11.97396614,  6.38529107])

In [114]:
BETAS + 1.96*(u_estandar) #Int.Conf sup

array([-1.88806992,  0.74973198,  0.09161156])

In [115]:
BETAS - 1.96*(u_estandar) #Int.Conf inf

array([-4.89300901,  0.53881218,  0.04857923])

#RESPUESTA
Para todos los intervalos de confianza son estadisticamente significativos dado que ninguno pasa por cero.